### ISSUE TITLE
autotools build error

### ISSUE THREAD

**Issue by Clownacy** [flamewing/mdtools#8]
I'm running into the problem described [here](https://stackoverflow.com/questions/25927742/why-syntax-error-near-unexpected-token-fi). Apparently it has to do with m4 macros not agreeing with Windows line-endings.

I recall Git having an option to force-convert txt files and the sort to CRLF, so there's probably a similar thing to disable it specifically for .m4 files.

**Comment by flamewing** [comment]
Just to be sure, you are trying to build on Windows with autotools. What toolchain are you using? MinGW? MinGW+msys? msys2?

I plan on testing build on Windows using msys2 toolchain, because it will easily allow me to add Windows CI using AppVeyor (and maybe even auto-build Windows releases), but I need time to do it.

**Comment by Clownacy** [comment]
msys2.

**Comment by flamewing** [comment]
Fixed by e5b3ab8df1e769f8495e2c0dfeb8800e21344d6a.
